// ComponentInfoGenerator.cs
// Proyecto: BlazOrbit.Generator  (netstandard2.0)
//
// PIPELINE OVERVIEW
// ─────────────────────────────────────────────────────────────────────────────
//  1. Lee todos los .razor como AdditionalFiles (texto plano).
//  2. Para cada .razor extrae: @namespace · @inherits · @attribute y el @code.
//  3. Parsea el @code con CSharpSyntaxTree (es C# puro) para obtener
//     [Parameter] + XML docs + default values.
//  4. Sólo los que tienen @attribute [GenerateComponentInfo] generan salida.
//  5. Resolución de herencia:
//       padre .razor → busca en el mapa de todos los .razor parseados
//       padre .cs    → busca en la Compilation de Roslyn (GetSymbolsWithName)
//       .cs → .cs   → sube BaseType en Roslyn sin límite hasta object
// ─────────────────────────────────────────────────────────────────────────────

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;

namespace BlazOrbit.Generator;

// ─────────────────────────────────────────────────────────────
//  Data models
// ─────────────────────────────────────────────────────────────

/// <summary>
/// Describes a single Blazor component parameter discovered at build time.
/// </summary>
/// <param name="Name">Parameter name.</param>
/// <param name="Type">CLR type name of the parameter.</param>
/// <param name="Default">Literal default value, if any.</param>
/// <param name="Description">XML doc summary, if available.</param>
public sealed record ParameterData(
    string Name,
    string Type,
    string? Default,
    string? Description);

/// <summary>
/// Aggregated metadata for a Blazor component extracted from its <c>.razor</c> file.
/// </summary>
/// <param name="Namespace">Declared namespace.</param>
/// <param name="ComponentName">Type name (derived from the file name).</param>
/// <param name="Parameters">Parameters declared in the <c>@code</c> block.</param>
public sealed record ComponentData(
    string Namespace,
    string ComponentName,
    ImmutableArray<ParameterData> Parameters);

/// <summary>Toda la información extraída de un único archivo .razor.</summary>
public sealed record RazorFileData(
    string FilePath,
    string ComponentName,        // del nombre de archivo
    string? DeclaredNamespace,    // de @namespace
    string? InheritsRaw,          // de @inherits (texto en crudo)
    ImmutableArray<ParameterData> OwnParameters,        // [Parameter] propios del @code
    bool GenerateInfo);        // true si @attribute [GenerateComponentInfo]

// ─────────────────────────────────────────────────────────────
//  Shared sources — se inyectan en la compilación de BlazOrbit
// ─────────────────────────────────────────────────────────────

internal static class SharedSources
{
    public const string GenerateComponentInfoAttribute =
        """
        // <auto-generated/>
        namespace BlazOrbit;

        /// <summary>
        /// Marks a Blazor component for automatic documentation generation.
        /// Add <c>@attribute [GenerateComponentInfo]</c> to the .razor file,
        /// or <c>[GenerateComponentInfo]</c> to a .cs component class.
        /// </summary>
        [System.AttributeUsage(System.AttributeTargets.Class,
            AllowMultiple = false, Inherited = false)]
        public sealed class GenerateComponentInfoAttribute : System.Attribute { }
        """;

    // Mismo namespace que el atributo → un solo "using BlazOrbit;" en los generados.
    public const string ComponentParameterInfo =
        """
        // <auto-generated/>
        #nullable enable

        namespace BlazOrbit;

        /// <summary>Describes a single Blazor component parameter.</summary>
        public sealed record ComponentParameterInfo(
            string  ParameterName,
            string  ParameterType,
            string? ParameterDefault,
            string? ParameterDescription);
        """;
}

// ─────────────────────────────────────────────────────────────
//  Diagnostics
// ─────────────────────────────────────────────────────────────

internal static class Diagnostics
{
    public static readonly DiagnosticDescriptor ComponentNameCollision = new(
        id: "BOBGEN001",
        title: "Multiple .razor components share the same simple name",
        messageFormat: "Multiple .razor files named '{0}' exist in different folders/namespaces ({1}); @inherits resolution prefers the same-namespace match and otherwise picks deterministically by file path. Rename one of them or fully-qualify @inherits to silence this warning.",
        category: "BlazOrbit.CodeGeneration",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public static readonly DiagnosticDescriptor AmbiguousBaseType = new(
        id: "BOBGEN002",
        title: "Ambiguous @inherits base type",
        messageFormat: "@inherits '{0}' matches multiple types in the compilation ({1}); resolution picked '{2}'. Fully-qualify @inherits with the namespace to silence this warning.",
        category: "BlazOrbit.CodeGeneration",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
}

// ─────────────────────────────────────────────────────────────
//  RazorIndex — multi-map of .razor files keyed by simple name
//  with collision detection. Built once per generation pass.
// ─────────────────────────────────────────────────────────────

internal sealed class RazorIndex
{
    private readonly Dictionary<string, List<RazorFileData>> _bySimpleName;

    public RazorIndex(IEnumerable<RazorFileData> files)
    {
        _bySimpleName = files
            .GroupBy(f => f.ComponentName, StringComparer.Ordinal)
            .ToDictionary(
                g => g.Key,
                g => g.OrderBy(f => f.FilePath, StringComparer.Ordinal).ToList(),
                StringComparer.Ordinal);
    }

    /// <summary>All entries with this simple name, deterministically sorted by file path.</summary>
    public IReadOnlyList<RazorFileData> Lookup(string simpleName)
        => _bySimpleName.TryGetValue(simpleName, out List<RazorFileData>? list)
            ? list
            : Array.Empty<RazorFileData>();

    /// <summary>
    /// Picks the best match for an @inherits resolved from <paramref name="consumerNamespace"/>.
    /// Same-namespace match wins; otherwise the first deterministic candidate.
    /// </summary>
    public RazorFileData? PickBest(string simpleName, string? consumerNamespace)
    {
        IReadOnlyList<RazorFileData> candidates = Lookup(simpleName);
        if (candidates.Count == 0)
        {
            return null;
        }

        if (candidates.Count == 1)
        {
            return candidates[0];
        }

        foreach (RazorFileData c in candidates)
        {
            if (StringComparer.Ordinal.Equals(c.DeclaredNamespace, consumerNamespace))
            {
                return c;
            }
        }

        return candidates[0];
    }

    /// <summary>Yields entries (simpleName, candidates) where there is more than one candidate.</summary>
    public IEnumerable<KeyValuePair<string, IReadOnlyList<RazorFileData>>> Collisions
    {
        get
        {
            foreach (KeyValuePair<string, List<RazorFileData>> kv in _bySimpleName)
            {
                if (kv.Value.Count > 1)
                {
                    yield return new KeyValuePair<string, IReadOnlyList<RazorFileData>>(kv.Key, kv.Value);
                }
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────
//  Generator
// ─────────────────────────────────────────────────────────────

/// <summary>
/// Roslyn incremental source generator that scans <c>.razor</c> files for
/// <c>[GenerateComponentInfo]</c> and emits per-component metadata classes.
/// </summary>
[Generator]
public sealed class ComponentInfoGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Inyectar el atributo y el DTO compartido en la compilación destino.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateComponentInfoAttribute.g.cs",
                SourceText.From(SharedSources.GenerateComponentInfoAttribute, Encoding.UTF8));
            ctx.AddSource("ComponentParameterInfo.g.cs",
                SourceText.From(SharedSources.ComponentParameterInfo, Encoding.UTF8));
        });

        // 2. Parsear TODOS los .razor como AdditionalFiles.
        //    Se necesitan todos para resolver cadenas de herencia entre .razor.
        IncrementalValuesProvider<RazorFileData> razorFiles = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase)
                && !Path.GetFileName(f.Path).Equals("_Imports.razor", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => RazorParser.Parse(file, ct))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);          // assert non-null para tipar el provider

        // Índice global de herencia .razor (se invalida solo cuando cambia algún .razor).
        IncrementalValueProvider<RazorIndex> razorIndex = razorFiles
            .Collect()
            .Select(static (arr, _) => new RazorIndex(arr));

        // Reportar colisiones de nombre (BOBGEN001) una sola vez por cambio en el índice.
        context.RegisterSourceOutput(razorIndex, static (spc, index) =>
        {
            foreach (KeyValuePair<string, IReadOnlyList<RazorFileData>> collision in index.Collisions)
            {
                string namespaces = string.Join(", ", collision.Value
                    .Select(f => f.DeclaredNamespace ?? "(no @namespace)")
                    .Distinct(StringComparer.Ordinal));
                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.ComponentNameCollision,
                    location: null,
                    collision.Key,
                    namespaces));
            }
        });

        // ── Pipeline A ───────────────────────────────────────────
        // Componentes que NO necesitan Compilation para resolver herencia:
        // sin @inherits, o cuya base se resuelve a otro .razor.
        IncrementalValuesProvider<(RazorFileData Razor, RazorIndex Index)> pipelineA = razorFiles
            .Combine(razorIndex)
            .Where(static pair =>
            {
                (RazorFileData razor, RazorIndex index) = pair;
                if (!razor.GenerateInfo)
                {
                    return false;
                }

                if (razor.InheritsRaw is null)
                {
                    return true;
                }

                string baseName = InheritanceResolver.ExtractSimpleName(razor.InheritsRaw);
                return index.PickBest(baseName, razor.DeclaredNamespace) is not null;
            });

        context.RegisterSourceOutput(pipelineA, static (spc, data) =>
        {
            (RazorFileData razor, RazorIndex index) = data;
            EmitComponentInfo(spc, razor, index, compilation: null);
        });

        // ── Pipeline B ───────────────────────────────────────────
        // Componentes cuya base es un tipo .cs → requieren Compilation.
        IncrementalValuesProvider<((RazorFileData Razor, RazorIndex Index) Left, Compilation Right)> pipelineB = razorFiles
            .Combine(razorIndex)
            .Combine(context.CompilationProvider)
            .Where(static pair =>
            {
                ((RazorFileData razor, RazorIndex index), _) = pair;
                if (!razor.GenerateInfo)
                {
                    return false;
                }

                if (razor.InheritsRaw is null)
                {
                    return false;
                }

                string baseName = InheritanceResolver.ExtractSimpleName(razor.InheritsRaw);
                return index.PickBest(baseName, razor.DeclaredNamespace) is null;
            });

        context.RegisterSourceOutput(pipelineB, static (spc, data) =>
        {
            ((RazorFileData razor, RazorIndex index), Compilation compilation) = data;
            EmitComponentInfo(spc, razor, index, compilation);
        });
    }

    private static void EmitComponentInfo(
        SourceProductionContext spc,
        RazorFileData razor,
        RazorIndex index,
        Compilation? compilation)
    {
        ImmutableArray<ParameterData> allParams = InheritanceResolver.Resolve(
            razor, index, compilation, spc.ReportDiagnostic);
        string ns = razor.DeclaredNamespace ?? "BlazOrbit.Components";
        ComponentData data = new(ns, razor.ComponentName, allParams);

        spc.AddSource(
            $"{razor.ComponentName}ComponentInfo.g.cs",
            SourceText.From(Emitter.Emit(data), Encoding.UTF8));
    }
}

// ─────────────────────────────────────────────────────────────
//  RazorParser — extrae datos de un archivo .razor
// ─────────────────────────────────────────────────────────────

/// <summary>
/// Parses a <c>.razor</c> <see cref="AdditionalText" /> to extract component metadata.
/// </summary>
public static class RazorParser
{
    private static readonly Regex s_nsRx =
        new(@"@namespace\s+(\S+)", RegexOptions.Compiled);

    // @inherits puede incluir genéricos: BOBVariantComponentBase<BOBButton, BOBButtonVariant>
    private static readonly Regex s_inheritsRx =
        new(@"@inherits\s+([^\r\n]+)", RegexOptions.Compiled);

    private static readonly Regex s_generateRx =
        new(@"@attribute\s+\[GenerateComponentInfo\]", RegexOptions.Compiled);

    private static readonly Regex s_codeStartRx =
        new(@"@code\s*\{", RegexOptions.Compiled);

    private static readonly CSharpParseOptions s_parseOptions =
        CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest);

    // ── Punto de entrada ─────────────────────────────────────

    /// <summary>
    /// Parses the given <c>.razor</c> file and returns structured metadata, or <see langword="null" /> if the file
    /// does not contain <c>@attribute [GenerateComponentInfo]</c>.
    /// </summary>
    /// <param name="file">Additional text representing the <c>.razor</c> file.</param>
    /// <param name="ct">Cancellation token.</param>
    public static RazorFileData? Parse(AdditionalText file, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        string? text = file.GetText(ct)?.ToString();
        if (string.IsNullOrEmpty(text))
        {
            return null;
        }

        string fileName = System.IO.Path.GetFileNameWithoutExtension(file.Path);
        string? ns = s_nsRx.Match(text!) is { Success: true } nm ? nm.Groups[1].Value.Trim() : null;
        string? inheritsRaw = s_inheritsRx.Match(text!) is { Success: true } im ? im.Groups[1].Value.Trim() : null;
        bool generateInfo = s_generateRx.IsMatch(text!);
        ImmutableArray<ParameterData> ownParams = ParseCodeBlock(text!, ct);

        return new RazorFileData(
            FilePath: file.Path,
            ComponentName: fileName,
            DeclaredNamespace: ns,
            InheritsRaw: inheritsRaw,
            OwnParameters: ownParams,
            GenerateInfo: generateInfo);
    }

    // ── Parseo del bloque @code { } ──────────────────────────

    private static ImmutableArray<ParameterData> ParseCodeBlock(string razorText, CancellationToken ct)
    {
        string? codeContent = ExtractCodeBlock(razorText);
        if (codeContent is null)
        {
            return ImmutableArray<ParameterData>.Empty;
        }

        // Envolvemos en una clase temporal: el bloque @code es C# puro, Roslyn lo parsea
        // perfectamente. Los usings hacen que los identificadores de atributo se resuelvan.
        string wrappedSource =
            "#nullable enable\n" +
            "using System;\n" +
            "using Microsoft.AspNetCore.Components;\n" +
            $"partial class __Temp__ {{\n{codeContent}\n}}";

        SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(wrappedSource, s_parseOptions, cancellationToken: ct);
        CompilationUnitSyntax root = syntaxTree.GetCompilationUnitRoot(ct);

        ClassDeclarationSyntax? classDecl = root.DescendantNodes()
                             .OfType<ClassDeclarationSyntax>()
                             .FirstOrDefault();

        if (classDecl is null)
        {
            return ImmutableArray<ParameterData>.Empty;
        }

        List<ParameterData> result = [];
        foreach (PropertyDeclarationSyntax prop in classDecl.Members.OfType<PropertyDeclarationSyntax>())
        {
            if (!IsParameterProperty(prop))
            {
                continue;
            }

            result.Add(new ParameterData(
                Name: prop.Identifier.Text,
                Type: prop.Type.ToString(),
                Default: prop.Initializer?.Value.ToString(),
                Description: XmlSummary(prop)));
        }

        return result.ToImmutableArray();
    }

    /// <summary>
    /// Extrae el contenido del bloque @code { } usando el lexer de Roslyn
    /// (<see cref="SyntaxFactory.ParseTokens"/>).  El conteo de llaves ignora
    /// automáticamente strings (incluidos verbatim, raw e interpolated), chars y
    /// comentarios, eliminando la fragilidad del parser manual basado en caracteres.
    /// </summary>
    public static string? ExtractCodeBlock(string content)
    {
        Match match = s_codeStartRx.Match(content);
        if (!match.Success)
        {
            return null;
        }

        // Posición de la llave '{' de apertura del @code
        int openBrace = match.Index + match.Length - 1;
        string tail = content.Substring(openBrace);

        int depth = 0;
        int tokenCount = 0;
        const int MaxTokens = 50_000;

        foreach (SyntaxToken token in SyntaxFactory.ParseTokens(tail))
        {
            if (token.IsKind(SyntaxKind.OpenBraceToken))
            {
                depth++;
            }
            else if (token.IsKind(SyntaxKind.CloseBraceToken))
            {
                depth--;
                if (depth == 0)
                {
                    return tail.Substring(1, token.Span.Start - 1);
                }
            }

            if (++tokenCount > MaxTokens)
            {
                break; // seguridad: archivo malformado o demasiado grande
            }
        }

        return null; // @code sin cerrar (archivo malformado)
    }

    // ── Helpers de sintaxis ──────────────────────────────────

    private static bool IsParameterProperty(PropertyDeclarationSyntax prop)
    {
        foreach (AttributeListSyntax attrList in prop.AttributeLists)
        {
            foreach (AttributeSyntax attr in attrList.Attributes)
            {
                string name = attr.Name.ToString();
                if (name is "Parameter" or "ParameterAttribute")
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static string? XmlSummary(PropertyDeclarationSyntax prop)
    {
        foreach (SyntaxTrivia trivia in prop.GetLeadingTrivia())
        {
            if (!trivia.HasStructure)
            {
                continue;
            }

            if (trivia.GetStructure() is not DocumentationCommentTriviaSyntax doc)
            {
                continue;
            }

            foreach (XmlNodeSyntax node in doc.Content)
            {
                if (node is not XmlElementSyntax el)
                {
                    continue;
                }

                if (el.StartTag.Name.ToString() != "summary")
                {
                    continue;
                }

                StringBuilder raw = new();
                foreach (XmlNodeSyntax cn in el.Content)
                {
                    raw.Append(cn.ToString());
                }

                // Quitar tags XML inline (<c>, <see cref="…"/>, etc.)
                string text = Regex.Replace(raw.ToString(), @"<[^>]+>", string.Empty);
                // Colapsar whitespace de summaries multilínea
                text = Regex.Replace(text, @"\s+", " ").Trim();

                return string.IsNullOrWhiteSpace(text) ? null : text;
            }
        }

        return null;
    }
}

// ─────────────────────────────────────────────────────────────
//  InheritanceResolver — recorre la cadena de herencia completa
// ─────────────────────────────────────────────────────────────

internal static class InheritanceResolver
{
    /// <summary>
    /// Devuelve todos los [Parameter] del componente (propios + heredados), en orden:
    /// primero los del tipo más derivado, luego los de sus bases sucesivas.
    ///
    /// Reglas de deduplicación:
    ///   Si un nombre ya aparece en una clase hija, se descarta en las clases padre.
    ///
    /// Cadenas soportadas:
    ///   .razor → .razor → .razor → …
    ///   .razor → .cs → .cs → …
    ///   (mezcla) .razor → .razor → .cs → .cs → …
    /// </summary>
    public static ImmutableArray<ParameterData> Resolve(
        RazorFileData root,
        RazorIndex razorIndex,
        Compilation? compilation,
        Action<Diagnostic> reportDiagnostic)
    {
        List<ParameterData> result = [];
        HashSet<string> seen = new(StringComparer.Ordinal);
        HashSet<string> visited = new(StringComparer.Ordinal); // protección anti-ciclo

        CollectFromRazor(root, razorIndex, compilation, seen, result, visited, reportDiagnostic);
        return result.ToImmutableArray();
    }

    // ── Recolección desde un nodo .razor ────────────────────

    private static void CollectFromRazor(
        RazorFileData component,
        RazorIndex razorIndex,
        Compilation? compilation,
        HashSet<string> seen,
        List<ParameterData> result,
        HashSet<string> visited,
        Action<Diagnostic> reportDiagnostic)
    {
        if (!visited.Add(component.ComponentName))
        {
            return; // anti-ciclo
        }

        // 1. Parámetros propios (en orden de declaración en el @code)
        foreach (ParameterData p in component.OwnParameters)
        {
            if (seen.Add(p.Name))
            {
                result.Add(p);
            }
        }

        // 2. Resolver base
        if (component.InheritsRaw is null)
        {
            return;
        }

        string baseName = ExtractSimpleName(component.InheritsRaw);

        // Same-namespace match wins; deterministic fallback otherwise.
        // Collisions already emitted as BOBGEN001 by the caller, so we don't
        // double-report here.
        RazorFileData? baseRazor = razorIndex.PickBest(baseName, component.DeclaredNamespace);
        if (baseRazor is not null)
        {
            CollectFromRazor(baseRazor, razorIndex, compilation, seen, result, visited, reportDiagnostic);
        }
        else if (compilation is not null)
        {
            // La base es un tipo .cs → cambiar a la rama Roslyn
            CollectFromCompilation(component.InheritsRaw, compilation, seen, result, reportDiagnostic);
        }
    }

    // ── Recolección desde un nodo .cs (Roslyn) ──────────────

    private static void CollectFromCompilation(
        string inheritsRaw,
        Compilation compilation,
        HashSet<string> seen,
        List<ParameterData> result,
        Action<Diagnostic> reportDiagnostic)
    {
        INamedTypeSymbol? symbol = FindType(compilation, inheritsRaw, reportDiagnostic);
        if (symbol is null)
        {
            return;
        }

        // Sube la jerarquía .cs completa hasta llegar a un tipo especial (object, etc.)
        INamedTypeSymbol? current = symbol;
        while (current is { SpecialType: SpecialType.None })
        {
            foreach (IPropertySymbol member in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (!seen.Add(member.Name))
                {
                    continue;
                }

                if (!IsParameter(member))
                {
                    continue;
                }

                result.Add(new ParameterData(
                    Name: member.Name,
                    Type: TypeString(member),
                    Default: DefaultValue(member),
                    Description: XmlSummaryFromSymbol(member)));
            }

            current = current.BaseType;
        }
    }

    // ── Helpers ──────────────────────────────────────────────

    /// <summary>
    /// Extrae el nombre simple a partir del texto en crudo del @inherits.
    ///
    ///   "BOBVariantComponentBase&lt;BOBButton, BOBButtonVariant&gt;" → "BOBVariantComponentBase"
    ///   "BlazOrbit.Components.BOBBase"                       → "BOBBase"
    ///   "BOBBase"                                                     → "BOBBase"
    /// </summary>
    internal static string ExtractSimpleName(string inheritsRaw)
    {
        string name = inheritsRaw.Trim();

        // Quitar genéricos
        int genericIdx = name.IndexOf('<');
        if (genericIdx > 0)
        {
            name = name.Substring(0, genericIdx);
        }

        // Quitar namespace
        int dotIdx = name.LastIndexOf('.');
        if (dotIdx >= 0)
        {
            name = name.Substring(dotIdx + 1);
        }

        return name.Trim();
    }

    /// <summary>
    /// Resuelve el símbolo del tipo base referenciado desde un <c>@inherits</c>.
    ///
    /// Estrategia:
    ///   1. Si el texto crudo está totalmente cualificado (<c>Ns.Sub.Type</c>),
    ///      usar <see cref="Compilation.GetTypeByMetadataName"/> directo —
    ///      es O(1) en la tabla de metadatos de Roslyn y determinista.
    ///   2. Si el texto es un nombre simple, escanear la compilación con
    ///      <c>GetSymbolsWithName</c>. Si hay más de un candidato, emitir
    ///      <c>BOBGEN002</c> y elegir el primero por nombre completo (orden
    ///      determinista).
    /// </summary>
    private static INamedTypeSymbol? FindType(
        Compilation compilation,
        string inheritsRaw,
        Action<Diagnostic> reportDiagnostic)
    {
        // Quitar genéricos para el lookup; aceptamos `Ns.Type<T1,T2>` y devolvemos
        // el tipo no construido — Roslyn nos da la definición igualmente.
        string nameNoGenerics = inheritsRaw.Trim();
        int genericIdx = nameNoGenerics.IndexOf('<');
        if (genericIdx > 0)
        {
            nameNoGenerics = nameNoGenerics.Substring(0, genericIdx).Trim();
        }

        // Fast path: fully qualified.
        if (nameNoGenerics.IndexOf('.') >= 0)
        {
            INamedTypeSymbol? fqn = compilation.GetTypeByMetadataName(nameNoGenerics);
            if (fqn is not null)
            {
                return fqn;
            }
        }

        // Fallback: simple name search across the whole compilation.
        string simpleName = ExtractSimpleName(inheritsRaw);
        List<INamedTypeSymbol> matches = compilation
            .GetSymbolsWithName(name => name == simpleName, SymbolFilter.Type)
            .OfType<INamedTypeSymbol>()
            .OrderBy(s => s.ToDisplayString(), StringComparer.Ordinal)
            .ToList();

        if (matches.Count == 0)
        {
            return null;
        }

        if (matches.Count > 1)
        {
            string candidates = string.Join(", ", matches.Select(s => s.ToDisplayString()));
            reportDiagnostic(Diagnostic.Create(
                Diagnostics.AmbiguousBaseType,
                location: null,
                simpleName,
                candidates,
                matches[0].ToDisplayString()));
        }

        return matches[0];
    }

    private static bool IsParameter(IPropertySymbol prop)
    {
        foreach (AttributeData attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "ParameterAttribute")
            {
                return true;
            }
        }

        return false;
    }

    private static readonly SymbolDisplayFormat s_typeFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static string TypeString(IPropertySymbol prop)
        => prop.Type.ToDisplayString(s_typeFormat);

    private static string? DefaultValue(IPropertySymbol prop)
    {
        foreach (SyntaxReference syntaxRef in prop.DeclaringSyntaxReferences)
        {
            if (syntaxRef.GetSyntax() is PropertyDeclarationSyntax { Initializer.Value: { } v })
            {
                return v.ToString();
            }
        }

        return null;
    }

    private static string? XmlSummaryFromSymbol(IPropertySymbol prop)
    {
        // Primary source: Roslyn's built-in extraction. Works across assemblies — if the referenced
        // assembly ships its .xml alongside the DLL, the summary comes through without syntax refs.
        string? documentationXml = prop.GetDocumentationCommentXml();
        if (!string.IsNullOrWhiteSpace(documentationXml))
        {
            string? parsed = ExtractSummaryFromDocXml(documentationXml!);
            if (!string.IsNullOrWhiteSpace(parsed))
            {
                return parsed;
            }
        }

        // Fallback: declaring-syntax trivia. Only reachable for symbols declared in the current
        // compilation whose GetDocumentationCommentXml returned empty (e.g. broken XML).
        foreach (SyntaxReference syntaxRef in prop.DeclaringSyntaxReferences)
        {
            SyntaxNode syntax = syntaxRef.GetSyntax();
            foreach (SyntaxTrivia trivia in syntax.GetLeadingTrivia())
            {
                if (!trivia.HasStructure)
                {
                    continue;
                }

                if (trivia.GetStructure() is not DocumentationCommentTriviaSyntax doc)
                {
                    continue;
                }

                foreach (XmlNodeSyntax node in doc.Content)
                {
                    if (node is not XmlElementSyntax el)
                    {
                        continue;
                    }

                    if (el.StartTag.Name.ToString() != "summary")
                    {
                        continue;
                    }

                    StringBuilder raw = new();
                    foreach (XmlNodeSyntax cn in el.Content)
                    {
                        raw.Append(cn.ToString());
                    }

                    string text = Regex.Replace(raw.ToString(), @"<[^>]+>", string.Empty);
                    text = Regex.Replace(text, @"\s+", " ").Trim();
                    return string.IsNullOrWhiteSpace(text) ? null : text;
                }
            }
        }

        return null;
    }

    private static string? ExtractSummaryFromDocXml(string xml)
    {
        try
        {
            // Roslyn wraps the summary in <member name="...">…</member>. Parse and pick <summary>.
            XDocument doc = XDocument.Parse(xml, LoadOptions.PreserveWhitespace);
            XElement? summary = doc.Root?.Element("summary");
            if (summary == null)
            {
                return null;
            }

            StringBuilder sb = new();
            FlattenDocNode(summary, sb);
            string text = Regex.Replace(sb.ToString(), @"\s+", " ").Trim();
            return string.IsNullOrWhiteSpace(text) ? null : text;
        }
        catch (XmlException)
        {
            return null;
        }
    }

    private static void FlattenDocNode(XNode node, StringBuilder sb)
    {
        switch (node)
        {
            case XText text:
                sb.Append(text.Value);
                break;
            case XElement el:
                switch (el.Name.LocalName)
                {
                    case "see":
                    case "seealso":
                        string? cref = el.Attribute("cref")?.Value;
                        string? langword = el.Attribute("langword")?.Value;
                        if (cref != null)
                        {
                            // Roslyn prefixes the cref with the member kind ("T:", "P:", "M:", ...). Strip it
                            // and keep only the last dotted segment so links collapse to a bare identifier.
                            int colon = cref.IndexOf(':');
                            string target = colon >= 0 ? cref.Substring(colon + 1) : cref;
                            int lastDot = target.LastIndexOf('.');
                            sb.Append(lastDot >= 0 ? target.Substring(lastDot + 1) : target);
                        }
                        else if (langword != null)
                        {
                            sb.Append(langword);
                        }

                        break;
                    default:
                        // <c>, <para>, <paramref>, unknown → recurse. Drops the surrounding tag, keeps text.
                        foreach (XNode child in el.Nodes())
                        {
                            FlattenDocNode(child, sb);
                        }

                        break;
                }

                break;
        }
    }
}

// ─────────────────────────────────────────────────────────────
//  Emitter — genera el string C# del archivo *ComponentInfo.g.cs
// ─────────────────────────────────────────────────────────────

internal static class Emitter
{
    public static string Emit(ComponentData data)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using BlazOrbit;");
        sb.AppendLine();
        sb.AppendLine($"namespace {data.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Auto-generated parameter docs for <c>{data.ComponentName}</c>.</summary>");
        sb.AppendLine($"public static partial class {data.ComponentName}ComponentInfo");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly ComponentParameterInfo[] Parameters =");
        sb.AppendLine("    [");

        foreach (ParameterData p in data.Parameters)
        {
            sb.AppendLine("        new(");
            sb.AppendLine($"            ParameterName:        \"{p.Name}\",");
            sb.AppendLine($"            ParameterType:        \"{p.Type}\",");
            sb.AppendLine($"            ParameterDefault:     {Literal(p.Default)},");
            sb.AppendLine($"            ParameterDescription: {Literal(p.Description)}");
            sb.AppendLine("        ),");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Literal(string? value)
        => value is null
            ? "null"
            : $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}